# Site wide configuration

title:            Ayu Dwi Septiana
locale:           en_US
#url:              http://localhost:4000
url:              http://ayudwi1995.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Ayu Dwi Septiana
  avatar: bio-photo.jpg
  bio: "Love your Self"
  email: 
  disqus-shortname: 
  twitter: ayudwi95 #username
  facebook: facebook.com/astridadeliana #username
  google:
    plus: Oh Sehun #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: ayudwi1995 #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: instagram.com/ayudwi95#username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: youtube.com/vlorybieber16#username
  soundcloud: soundcloud.com/ayudwi1995#username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
